#!/bin/bash
set -euo pipefail

# omarchy-config-verify installer
#
# First run asks a few questions (dotfiles repo URL, install location, hook)
# and saves the answers to ~/.config/omarchy-config-verify.conf. Later runs
# reuse that config. Re-ask anytime with --reconfigure.

PROJECT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
SCRIPT_SRC="$PROJECT_DIR/omarchy-config-verify"
HOOK_SRC="$PROJECT_DIR/hooks/post-update/verify-config.hook"
BIN_DIR="$HOME/.local/bin"
HOOK_TYPE="post-update"
CONF_FILE="${OMARCHY_CONFIG_VERIFY_CONF:-$HOME/.config/omarchy-config-verify.conf}"

RECONFIGURE=0
if [[ ${1:-} == "--reconfigure" ]]; then
  RECONFIGURE=1
fi

command -v omarchy &>/dev/null || {
  echo "warning: 'omarchy' CLI not found. This tool targets Omarchy systems." >&2
}

# --- Prompt for missing configuration on first run ---------------------------
# Note: read -rp writes the prompt to stderr and reads stdin directly, which is
# robust in any terminal. Command substitution ($(prompt ...)) corrupts input
# under a pty, so values are captured explicitly instead.

if [[ -f "$CONF_FILE" && $RECONFIGURE -ne 1 ]]; then
  . "$CONF_FILE"
  echo "Using existing config: $CONF_FILE"
  echo "  DOTFILES_REPO=$DOTFILES_REPO"
  echo "  DOTFILES_DIR=$DOTFILES_DIR"
  echo "  INSTALL_HOOK=$INSTALL_HOOK"
elif [[ ! -t 0 ]]; then
  echo "Non-interactive shell, no config found. Using defaults; set env vars or"
  echo "edit $CONF_FILE to override."
  DOTFILES_REPO="${DOTFILES_REPO:-}"
  DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
  INSTALL_HOOK="${INSTALL_HOOK:-yes}"
else
  echo "First-run setup — a few questions to get started."
  echo "(leave a prompt empty to use the default; Ctrl-C aborts)"
  echo
  DOTFILES_REPO="${DOTFILES_REPO:-}"
  read -rp "Dotfiles git repo URL (cloned into your home, e.g. https://github.com/user/dotfiles.git): " input
  DOTFILES_REPO="${input:-$DOTFILES_REPO}"
  read -rp "Directory to use as your dotfiles repo [${DOTFILES_DIR:-$HOME/dotfiles}]: " input
  DOTFILES_DIR="${input:-${DOTFILES_DIR:-$HOME/dotfiles}}"
  read -rp "Install the post-update hook? (auto-verifies after every omarchy update) [${INSTALL_HOOK:-yes}]: " input
  INSTALL_HOOK="${input:-${INSTALL_HOOK:-yes}}"
fi

# --- Clone / refresh the dotfiles repo ---------------------------------------
if [[ -n ${DOTFILES_REPO:-} ]]; then
  if [[ -d "$DOTFILES_DIR/.git" ]]; then
    echo "Dotfiles repo already exists at $DOTFILES_DIR — leaving it as-is."
    echo "  (run 'git -C $DOTFILES_DIR pull' to refresh it)"
  else
    echo "Cloning $DOTFILES_REPO into $DOTFILES_DIR..."
    mkdir -p "$(dirname "$DOTFILES_DIR")"
    git clone "$DOTFILES_REPO" "$DOTFILES_DIR" || {
      echo "error: clone failed. Fix the URL or create the repo directory." >&2
      exit 1
    }
  fi
else
  echo "No dotfiles repo URL given; using existing $DOTFILES_DIR if present."
fi

# --- Persist config ----------------------------------------------------------
if [[ -f "$CONF_FILE" && $RECONFIGURE -ne 1 ]]; then
  : # config already on disk
else
  mkdir -p "$(dirname "$CONF_FILE")"
  cat > "$CONF_FILE" <<EOF
# omarchy-config-verify configuration (generated by install.sh)
DOTFILES_REPO="$DOTFILES_REPO"
DOTFILES_DIR="$DOTFILES_DIR"
INSTALL_HOOK="$INSTALL_HOOK"
EOF
  echo "Saved config: $CONF_FILE"
fi

# --- Install the command ------------------------------------------------------
echo "Installing omarchy-config-verify to $BIN_DIR..."
mkdir -p "$BIN_DIR"
install -m 755 "$SCRIPT_SRC" "$BIN_DIR/omarchy-config-verify"
echo "  installed: $BIN_DIR/omarchy-config-verify"

# --- Install the post-update hook ---------------------------------------------
if [[ ${INSTALL_HOOK:-yes} =~ ^(y|Y|yes|Yes|YES)$ ]]; then
  echo "Installing $HOOK_TYPE hook..."
  if command -v omarchy &>/dev/null && omarchy hook install --help &>/dev/null 2>&1; then
    omarchy hook install "$HOOK_TYPE" "$HOOK_SRC"
  else
    HOOK_DIR="$HOME/.config/omarchy/hooks/$HOOK_TYPE.d"
    mkdir -p "$HOOK_DIR"
    install -m 755 "$HOOK_SRC" "$HOOK_DIR/$(basename "$HOOK_SRC")"
    echo "  installed: $HOOK_DIR/$(basename "$HOOK_SRC")"
  fi
else
  echo "Skipping $HOOK_TYPE hook (INSTALL_HOOK=$INSTALL_HOOK)."
fi

echo
echo "Done. Next steps:"
echo "  omarchy-config-verify              # check current state (report only)"
echo "  omarchy-config-verify --apply      # restore anything an update changed"
echo "  omarchy update                     # auto-verifies via the post-update hook"
echo
echo "Re-run setup questions with: $0 --reconfigure"
